### PR TITLE
added comandline interface (cli) badge

### PR DESCRIPTION
**Pull request by Cube707**
Terminalbadge

I wanted a badge like this for a comandline tool I put on GitHub recently, so I created it.

I am not sure if this is too non-specific, but I belive it would have uses. Your call if you want to add it.

### Licence

I created the svg myself, so it's completly open to use

### CODE REVIEW

**Comment by aleen42** [comment]
How about naming it as `Terminal`? But `CLI` is good for me, thx.

**Comment by Cube707** [comment]
Yeah Terminal is a good idea. I could have come up with that myself 😅😂

Will change later👍

**Comment by Cube707** [comment]
@aleen42 updated and ready

**Comment by aleen42** [comment]
> Yeah Terminal is a good idea. I could have come up with that myself 😅😂
> 
> Will change later👍

Sorry, I preferred to adapt `CLI` because `terminal` is only defined under Mac or Linux? Thanks for your contributions again.

**Pull request merged**
